- include/cswap.h
- suppl/compat/dos.h
This proposed patch fixes a problem which (on my machine) was causing FreeCOM compiled with `xms-swap gcc` to swap only part of the transient stack area --- rather than the whole stack --- to XMS, and back.  The bug ultimately would cause FreeCOM to crash when one tries to `EXIT` from the shell.
Thank you!
> Fix: ia16-elf-gcc code wrongly assumed XMS driver preserves %bx

- shell/command.c
As a result of [fixing a `gcc-ia16` bug in the `asm` clobber list handling](https://github.com/tkchia/gcc-ia16/commit/7d89c99e279b44a582e5a31ebe43219fbbcae2c2), I found another place in FreeCOM where an `asm` input operand was (incorrectly) overlapping with its clobber list.  This patch should fix this.
Thank you!
> Fix: keep asm inputs & clobbers separate in gcc port of dup2

- suppl/src/intr.asm
This fixes the `[Out of memory loading STRINGS.]` problem I encountered when running FreeCOM under DOSBox 0.74, as I mentioned [on `freedos-devel`](https://www.mail-archive.com/freedos-devel@lists.sourceforge.net/msg11641.html) --- at least when FreeCOM is compiled with GCC.
I have not yet figured out how best to patch `intr( )` to load flags for the Open Watcom case.
Thank you!
> ia16-elf-gcc: intr( ) now loads flags before invoking interrupt

- shell/loadhigh.c
to reproduce the issue:
1. Create zero-byted free memory arena (in conventional or upper memory block)
2. LH some_command
3. The system will somewhat go wrong
Boot FD image for the test  : [test_zerobytes_freemem.zip](https://github.com/FDOS/freecom/files/3276728/test_zerobytes_freemem.zip)
> Fix loadhigh failure when zero-byte free memory block is exist

- shell/command.c
Allow non-permanent command.com instances to exit with the last errorlevel instead of always zero.
> Allow shell to exit with the last errorlevel instead of always zero.

- strings/FINNISH.ERR
- strings/FINNISH.LNG
This commit adds FINNISH.LNG and FINNISH.ERR to STRINGS, which serve as the Finnish translation for FreeCOM
Both files are encoded for code page 850, which is the code page used for Finnish. The only two special characters are ä/ö, the encodings of which coincide across many code pages (including 437).
> Add Finnish translation to FreeCOM

- strings/ukr.lng
Was causing extra and untranslated string in ukrainian.
> Translations: language keyword got renamed [#48]

- cmd/cls.c
- cmd/ctty.c
- include/misc.h
- lib/cbreak.c
- lib/readcmd.c
* redirect critical error prompt to correct device
* CLS command will work with common serial terminal
* (workaround) use plain readcommandDOS for non-standard CON device
> fix CTTY suitable for serial terminal via AUX (COMn)

- strings/turkish.err
- strings/turkish.lng
This commit fixes the critical error of not recognising prompt reply keys. Without this, it is not possible to reply to prompts, unless the user knows about YyNn.
Plus some more improvements and simplifications.
It would be really great if this could make it into the final FDOS 1.3 release.
> Fix Turkish translations

- suppl/fmemory.h
- suppl/src/fmemcpy.c
- suppl/src/fmemove.c
Since ia16-elf-gcc's libi86 received support for fmemcpy, fmemmove
and fmemset, its prototypes are in conflict with the replacement
functions defined in the suppl directory. If libi86 implements all
of the support required for FreeCOM in the future, then we may not
need to include suppl, but until then adjust the suppl to match the
common prototypes.
Patch by @tkchia, and discussion at [fixes #79]
> Supplement: Match fmem* functions to common prototypes

- suppl/compat/dos.h
- suppl/p-gcc.h
- suppl/p-watcom.h
- suppl/regproto.h
- suppl/src/intr.asm
See https://github.com/FDOS/freecom/pull/80#issuecomment-1232741956 .
> Supplement: rename intr( ) to intrf( )/_intrf( ), and make its prototype agree with the corresponding functions in Open Watcom and (gcc-ia16 +) libi86

- strings/strings.mak
The order of variable assignment seems to be important in Watcom make
fixes #88
> Correct the order of variable assignment in strings\strings.mak

- cmd/copy.c
Bug apparently in 6f764c2065fa6ffc3cbeba18043d9a4d0e22a00c
> COPY: allow lowercase drive letter for destination

- build.bat
- lib/exec.c
> Cmdline fix

- scripts/echoto.bat
This allows the build to succeed on MS-DOS 6.22 where a subshell's environment isn't big enough. Patch shamelessly copied from https://github.com/FDOS/kernel/commit/d6c50ebbe6.
> Build: Use revised echoto batch file from kernel

- mkfiles/watcom.mak
set wlib options and LIBLIST variable to be portable over all Open Watcom versions
> Open Watcom fix wlib listing handling

- scripts/echolib.bat
- scripts/echoto.bat
- change to be similar as echoto.bat nethod
- no more then 10 parameters are used
- add arguments overflow check to echolib.bat
- add arguments overflow check to echoto.bat
> build: modify echolib.bat to minimize environment use and args check

- .gitignore
- build.bat
- build.sh
- ci_build.sh
- clean.bat
- clean.sh
- cmd/cmd.m1
- cmd/makefile
- cmd/makefile.mak
- criter/makefile.mak
- lib/lib.m1
- lib/makefile
- lib/makefile.mak
- shell/command.m1
- shell/makefile
- shell/makefile.mak
- strings/makefile.mak
- strings/strings/makefile.mak
- suppl/makefile.mak
- suppl/src/makefile.mak
- utils/makefile.mak
unify main make file name to makefile.mak
now make tool command line is handled by MAKE environment variable (fix issue with space after -f for Turbo C)
> build: fix make tool command line handling

- ci_build.sh
- include/cswap.h
- include/resource.h
- lib/makefile.mak
- lib/mk_rddir.c
- scripts/echolib.bat
- scripts/echoto.bat
- shell/cswapc.c
- shell/init.c
- shell/makefile.mak
- strings/strings/makefile.mak
I've added Turbo C 2.01 to the CI, but as yet we don't have access to the compiler there. I have in mind to create an encrypted tarball which we can decrypt in the CI using github actions secrets facility, unless someone else wants to host an unencrypted version somewhere?
Notes:
1/ Firstly I've reverted the echolib changes as per the discussion at #117
2/ If you have the Turbo C installed at c:\tc201 in your dosemu C drive, then running the ci_build script will also perform the a TC2 builds.
> Tc build fixes 01

- cmd/verify.c
- include/cswap.h
- lib/exec.c
- suppl/p-watcom.h
- suppl/suppl.h
using ISO standard compiler reserved words form of #pragma aux
> Open-Watcom: use safer form of #pragma aux

- mkfiles/bc5.mak
- mkfiles/gcc.mak
- mkfiles/tc2.mak
- mkfiles/turbocpp.mak
- mkfiles/watcom.mak
- shell/makefile.mak
now it is handled transparent way by use of response file only if necessary that it can be changed from response file to command line passing arguments
> build: remove # comment like handling linker command

- .github/workflows/ci-build.yml
- ci_prereq.sh
- cmd/makefile.mak
@PerditionC I see this GPG encrypted file method as a proof of concept, it works but is far from ideal. I really want all PRs to be checked with Turbo C 2.01, not just those users that have access to the passphrase (you can find that in https://github.com/FDOS/freecom/settings/secrets/actions to copy to your own repo). For this to happen the TC201.tar unencrypted file needs to be hosted somewhere else public.
Note: add the secret TC201_SYMMETRIC_PASSPHRASE to your own freecom github repository secrets to get your PRs built with Turbo C, otherwise they will only be checked fully **after** they have been merged.
> CI: Turbo C 2.01 get and decrypt

- cmd/makefile.mak
- lib/makefile.mak
- mkfiles/bc5.mak
- mkfiles/tc2.mak
- mkfiles/turbocpp.mak
- scripts/echolib.bat
- suppl/src/makefile.mak
fix special handling of (&) character for Windows cmd.exe shell fix (+)add character handling
remove useless second list for librarian, now handled in echolib.bat without any environment variable
> build: fix build by tlib and response file (Borland tlib)

- build.bat
- build.sh
- mkdist.bat
- utils/makefile.mak
- utils/ptchsize.c
ptchsize is build tool (used by FREECOM build) and also DOS target tool
now
- in tools (DOS tools included in distribution) is DOS version 
- in utils (host native tools used by FREECOM build) is host OS version
> build: add ptchsize as native build for cross-compilation

- mkfiles/gcc.mak
- mkfiles/watcom.mak
- utilsc/makefile.mak
gcc doesn't support compact memory model
configuration handle this special case by generating appropriate message, now it happens only for fixstrs.exe (in strings)
Open Watcom can be run from Windows or Linux or DOS
only necessary is define WATCOM env. variable and add host OW binaries on the PATH, all other is handled by make files
> build: fix cross-compile setup for gcc and Open Watcom

- clean.bat
- clean.sh
- config.std
- mkfiles/bc5.mak
- mkfiles/tc2.mak
- mkfiles/turbocpp.mak
- strings/fixstrs.c
- strings/makefile.mak
- strings/strings/makefile.mak
the format of the response file depends on the compiler used, which is not generally correct for cross-compilation
the program has been modified to define the file format via a command line option, making the file creation transparent and defined to be correct for currently used tool
> fix cross-compilation build of fixstrs.exe

- cmd/mkdir.c
- cmd/rmdir.c
- include/misc.h
- lib/mk_rddir.c
doesn't use static symbol name in prototype or parameter name, it is confusing
> cleanup code to be more transparent

- suppl/src/mcb_walk.c
Current lMS-DOS still reports its version as v4.00 but does fully support a DOS-managed UMA. As of today lMS-DOS also supports the SHELLHIGH= directive. Like FreeDOS's this is implemented using the 21.4B80 extension. Although the internals differ, the outside observable behaviour is the DOS executable loader allocates both the environment and the process memory block into the UMA, if there are free UMBs. However, unlike LH the UMB link state is not enabled once the control flow is passed to the application. That means an environment block in a UMB isn't reachable when walking the MCBs without regard to proceeding past the first UMCB.
The MCB walker is used in FreeCOM's init to validate the environment block passed to it upon its startup. Reference: …
> mcb_walk.c: try querying UMB link state even if not on DOS 5+

- shell/loadhigh.c
Reference: https://github.com/FDOS/freecom/issues/166
There is one remaining oddity: If an out of bounds region is selected with eg `/L:4` then the 3rd region is partially freed whereas I would expect it to be fully reserved like the 1st and 2nd regions. Log of a test session:
```
&; Welcome to lDebug!
Press any key to enter debugger terminal!
Timer stopped
V0=000000A5 V1=00000000 V2=00000000 V3=00000000  DCO=00000000 DCS=00000000
V4=00000000 V5=00000000 V6=00000000 V7=00000000  DAO=0000F007 DAS=0000F007
V8=00000000 V9=00000000 VA=00000000 VB=00000000  DIF=0180F008 DPI=0000:0000
VC=00000000 VD=00000000 VE=00000000 VF=00000000  DPR=7601     DPP=0000
Current mode: Virtual 86 Mode
-ldos
-q
Starting small lDOS (2025 February) based on MS-DOS v4.01
dosemu XMS 3.0 & UMB support enabled
init: …
```
> ecm loadhigh

- cmd/dir.c
- lib/lfnfuncs.c
- lib/prprompt.c
- suppl/src/_getdcwd.c
- suppl/src/dfntruen.c
Between the current lDOS kernel (which doesn't support 21.73), SRDISK, and dosemu2 revision 6a2f4f527 the return from 21.7303 somehow is with both Carry Flag and AX preserved. This makes the DIR command think that the call is supported when it isn't.
The proper check is to call with CY set before the call.
> set CY before calling 21.71 or 21.73 DOS functions (LFN, FAT32)

- strings/DEFAULT.err
- strings/DEFAULT.lng
Part of patch
~~~
commit 01c4ad0a496797e74fccee2e5ae61244f8e4e641
Author: Sebastian Rasmussen <sebras@gmail.com>
Date:   Thu Apr 10 00:21:02 2025 +0200
Fix typos in the original English files for many projects.
~~~
> Import textual fixes from fd-nls [closes #174]

- ci_prereq.sh
Sometimes DOS packages can have upper or mixed case filenames that Linux unzip doesn't recognise as needing downcasing.
> CI: Force lower case when unzipping
